### ISSUE TITLE
How can i add onLongPress Listener

### ISSUE THREAD

**Issue by ervinod** [imablanco/Zoomy#12]
Hello there,
There is no method to detect if user has long pressed on image,  so how can I add onDoubleTap and onLongClick Listener to view ...pls help me.....

**Comment by imablanco** [comment]
Added in the next library release this Sunday

**Comment by ervinod** [comment]
Thanks for quick response.... waiting for next release

**Comment by Krutika-chotara** [comment]
i am still not able to detect on click listener using 1.1.0 version
