### ISSUE TITLE
status bar gets lost

### ISSUE THREAD

**Issue by Aksh0377** [imablanco/Zoomy#16]
when we zoom the image status bar of app gets lost.

**Comment by imablanco** [comment]
Thia is the default behavior if you do not disable immersive mode which is enabled by default.
To disable it provide a ZoomyConfig object with the correct configuration.
 ZoomyConfig config = new ZoomyConfig();
config.setImmersiveModeEnabled(false);

**Comment by Aksh0377** [comment]
Hi Alvaro,
Thanks for your reply firstly, and I have already tried this but it
isn't working. please let me know if you have any other suggestions.

Thanks,
Soni Axay.

Keep Learning...

**Comment by imablanco** [comment]
Please @Aksh0377 paste your code so I can figure out why is happening.
