### ISSUE TITLE
Dialog Fragment

### ISSUE THREAD

**Issue by TurKorsaN** [imablanco/Zoomy#2]
When using in DialogFragment, ZoomableView stays under DialogFragment. And i can't see the image.

**Comment by imablanco** [comment]
The library uses Activity's decor view to place the target view on top of everything but Dialogs in Android are shown creating another Window above current the current one.
I will try to figure out how to resolve this issue.
If someone has any idea how to deal with this any help will be appreciated.

**Comment by TurKorsaN** [comment]
I made my own implementation but I didn't tested it very well.

**Comment by imablanco** [comment]
Feel free to make a pull request then.

**Comment by ZachBublil** [comment]
Have you overcome this issue?

**Comment by LawrenceStent** [comment]
Do you have a solution for this yet? Rather important to have this working if I'm to use it in our project.

**Comment by imablanco** [comment]
@ZachBublil @LawrenceStent Sorry but I have no time right now to handle any issues. @TurKorsaN mentioned that he managed to resolve it, so maybe he can offer some help

**Comment by LawrenceStent** [comment]
It's fine I changed my implementation to the of a normal fragment. If anyone else is looking at this then this is an option, however having a zoom on a dialog may not be possible with this library.

**Comment by imablanco** [comment]
Hi everyone I managed to solve the issue partially by drawing the zoomed View over the Dialog's window, but because of the nature of them, depending on their window configuration, they may be drawn on not-full screen windows, so the zoomed View will never scale over the whole screen in these cases. Fullscreen Dialogs tested works well.

**Comment by akshitpsutariya** [comment]
> The library uses Activity's decor view to place the target view on top of everything but Dialogs in Android are shown creating another Window above current the current one.
> I will try to figure out how to resolve this issue.
> If someone has any idea how to deal with this any help will be appreciated.

I have faced the same problem

**Comment by imablanco** [comment]
Hi @akshitpsutariya you should be able to construct the Zoomy builder with a Dialog instance to get the decor view from its Window.
