### ISSUE TITLE
Image Freeze in multi touch(more than 2 fingers)

### ISSUE THREAD

**Issue by sumitsonawane** [imablanco/Zoomy#24]
If device having touch gesture(3 fingers swipe) screenshot enabled then Image Freezes on Screen

**Comment by page1group** [comment]
I hope this code help someone pained multi touch.

We should custom `ZoomableTouchListener`'s onTouch().

Just change
 `if (mAnimatingZoomEnding || ev.getPointerCount() > 2) return true;`
-> 
 `if (mAnimatingZoomEnding || ev.getPointerCount() > 2) {
            mEndingZoomAction.run();
            return true;
        }`

**Comment by sumitsonawane** [comment]
> I hope this code help someone pained multi touch.
> 
> We should custom `ZoomableTouchListener`'s onTouch().
> 
> Just change
> `if (mAnimatingZoomEnding || ev.getPointerCount() > 2) return true;`
> ->
> `if (mAnimatingZoomEnding || ev.getPointerCount() > 2) { mEndingZoomAction.run(); return true; }`

@imablanco can you try this?

**Comment by sumitsonawane** [comment]
@page1group thanks for the update.... its works..

**Comment by imablanco** [comment]
Will try this weekend but it seems very straightforward so I am planning to merge it anyway. Sorry for the delay but I barely have time to check spare projects.

**Comment by sumitsonawane** [comment]
> Will try this weekend but it seems very straightforward so I am planning to merge it anyway. Sorry for the delay but I barely have time to check spare projects.

ok, thanks.

**Comment by mustafakuloglu** [comment]
I am also facing this problem. Can you merge #30 if you have time?

**Comment by GorkemKarayel** [comment]
when can you merge ? @imablanco

**Comment by pratikmhatre** [comment]
> 
> 
> I hope this code help someone pained multi touch.
> 
> We should custom `ZoomableTouchListener`'s onTouch().
> 
> Just change
> `if (mAnimatingZoomEnding || ev.getPointerCount() > 2) return true;`
> ->
> `if (mAnimatingZoomEnding || ev.getPointerCount() > 2) { mEndingZoomAction.run(); return true; }`

This solution works great, I just have a small addition to it, to make the zoom out experience better,


` if (mAnimatingZoomEnding || ev.getPointerCount() > 2) {
            if (ev.getPointerCount() > 2) {
                mEndingZoomAction.run();
            }
            return true;
        }`
