### ISSUE TITLE
Could not apply zoomy inside an adapter

### ISSUE THREAD

**Issue by snajdovski** [imablanco/Zoomy#28]
I tried implementing zoomy using the documentation and for some reason, I can't implement it inside an adapter, am I doing some error here?
```
 Zoomy.Builder builder = new Zoomy.Builder(AdvancedItemListAdapter.this)
                    .target(holder.mItemImg);
            builder.register();

```

**Comment by snajdovski** [comment]
Getting that I can't resolve constructor

**Comment by imablanco** [comment]
You need to pass a valid window container (Activity, Dialog...) to Builder constructor. Seems you are passing just the adapter instance.
