### ISSUE TITLE
hold zoom level

### ISSUE THREAD

**Issue by sagarnayak** [imablanco/Zoomy#31]
when an image is zoomed and the finger is lifted it comes to the initial state. I want to keep that at the level and come back to the initial state on double-tap. how to do that?

**Comment by imablanco** [comment]
Sorry but this is not possible due to the library design and there are no plans in the mid term to change this behavior.

**Comment by SurenAvagyanG** [comment]
I was using your package, but it seems I need to change it after this answer :+1: 
1 download/user/customer +- shouldn't be disturbing for you.
