### ISSUE TITLE
Zoomy in RecyclerView

### ISSUE THREAD

**Issue by nativ18** [imablanco/Zoomy#7]
Hello guys,

Can you please explain how I can unregister zoomy from a view in RecyclerView?  the problem is that I have many types of view, on some of them I want to be able to apply zoom and on some I don't. Because the recycling mechanism I'm getting zooming ability on views that I don't want.

**Comment by imablanco** [comment]
Hi, I am scheduling this and other issues for when I have a some time. 
Meanwhile, Zoomy works by setting a custom touch listener to the View, so setting the touch listener of the non zoomable Views to null or any other TouchListener implementation will work.
